services:
  skins3d:
    container_name: samskins
    image: git.lionx.me/aborady/samskins:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      FAL_API_KEY: ${FAL_API_KEY}
      ACCESS_PASSWORD: ${ACCESS_PASSWORD}
      SHOW_CONTROLS: false
      PORT: 3000
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true

